services:
  web:
    build: .
    environment:
      - OPENAI_API_KEY
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
      - GROQ_API_KEY
      - TOKENIZERS_PARALLELISM
      - REDIS_URL
      - REDIS_PASSWORD
      - REDIS_PORT
      - REDIS_USERNAME
      - MXBAI_API_KEY
      - RESEND_API_KEY
      - RESEND_NOREPLY
      - GEMINI_API_KEY
      - CLIENT_MODE
      - MISTRAL_API_KEY

    ports:
      - "8080:8080"
